version: '3.7'

services:
  pyredis:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      mode: replicated
      replicas: 2
      labels:
        - "traefik.docker.network=traefik-public"
        - "traefik.enable=true"
        - "traefik.http.services.pyredis.loadbalancer.server.port=9000"
        - "traefik.http.routers.pyredis.rule=Host(`pyredis.iwpnd.pw`)"
        - "traefik.http.routers.pyredis.entrypoints=http,https"
        - "traefik.http.routers.pyredis.tls.certresolver=certbot"
    networks:
      - example-network
      - traefik-public
    ports:
      - 8501:8501
  redis:
    image: redis:alpine
    networks:
      - example-network

networks:
  example-network:
    attachable: true
  traefik-public:
    external: true