version: '3.7'

services:
  pyredis:
    build: ./app
    image: docker.pkg.github.com/iwpnd/aws-swarm-app/awsexample:latest
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.docker.network=traefik-public
        - traefik.enable=true
        - traefik.http.services.pyredis.loadbalancer.server.port=80
        - traefik.http.routers.pyredis.rule=Host(`pyredis.titan.iwpnd.pw`)
        - traefik.http.routers.pyredis.entrypoints=http,https
        - traefik.http.routers.pyredis.tls.certresolver=certbot
    networks:
      - example-network
      - traefik-public
  redis:
    image: redis:alpine
    networks:
      - example-network

networks:
  example-network:
    attachable: true
  traefik-public:
    external: true